"""Alter users

Revision ID: 058f74b1f51d
Revises: 5366f9a10cb4
Create Date: 2024-10-22 11:47:00.027590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058f74b1f51d'
down_revision: Union[str, None] = '5366f9a10cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_reply', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reply_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reply_delay')
    op.drop_column('users', 'auto_reply')
    # ### end Alembic commands ###
